# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(307, 423)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(193, 215, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(193, 215, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Canvas = QtWidgets.QGraphicsView(self.centralwidget)
        self.Canvas.setGeometry(QtCore.QRect(10, 30, 280, 280))
        self.Canvas.setMouseTracking(False)
        self.Canvas.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Canvas.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Canvas.setObjectName("Canvas")
        self.Execute = QtWidgets.QPushButton(self.centralwidget)
        self.Execute.setGeometry(QtCore.QRect(10, 340, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(True)
        font.setWeight(75)
        self.Execute.setFont(font)
        self.Execute.setObjectName("Execute")
        self.PredictionIs = QtWidgets.QLabel(self.centralwidget)
        self.PredictionIs.setGeometry(QtCore.QRect(200, 340, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(True)
        font.setWeight(75)
        self.PredictionIs.setFont(font)
        self.PredictionIs.setTextFormat(QtCore.Qt.AutoText)
        self.PredictionIs.setScaledContents(False)
        self.PredictionIs.setAlignment(QtCore.Qt.AlignCenter)
        self.PredictionIs.setObjectName("PredictionIs")
        self.PredictionValue = QtWidgets.QLabel(self.centralwidget)
        self.PredictionValue.setGeometry(QtCore.QRect(200, 350, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(21)
        self.PredictionValue.setFont(font)
        self.PredictionValue.setAlignment(QtCore.Qt.AlignCenter)
        self.PredictionValue.setObjectName("PredictionValue")
        self.DrawHere = QtWidgets.QLabel(self.centralwidget)
        self.DrawHere.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(True)
        font.setWeight(75)
        self.DrawHere.setFont(font)
        self.DrawHere.setObjectName("DrawHere")
        self.Clear = QtWidgets.QPushButton(self.centralwidget)
        self.Clear.setGeometry(QtCore.QRect(270, 10, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(True)
        font.setWeight(75)
        self.Clear.setFont(font)
        self.Clear.setObjectName("Clear")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Execute.setText(_translate("MainWindow", "Predict"))
        self.PredictionIs.setText(_translate("MainWindow", "Prediction is:"))
        self.PredictionValue.setText(_translate("MainWindow", "N/A"))
        self.DrawHere.setText(_translate("MainWindow", "Draw Here:"))
        self.Clear.setText(_translate("MainWindow", "X"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
